<?php

namespace App\Enums;

enum AuditAction: string
{
    case LOGIN = 'LOGIN';
    case LOGOUT = 'LOGOUT';
    case UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
    case DOWNLOAD_DOCUMENT = 'DOWNLOAD_DOCUMENT';
    case VIEW_DOCUMENT = 'VIEW_DOCUMENT';
    case UPDATE_PROFILE = 'UPDATE_PROFILE';
    case SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';
    case VERIFY_DOCUMENT = 'VERIFY_DOCUMENT';
    case ASSIGN_ASSESSOR = 'ASSIGN_ASSESSOR';
    case ASSESS_CPMK = 'ASSESS_CPMK';
    case CHANGE_VATC = 'CHANGE_VATC';
    case CREATE_TEST = 'CREATE_TEST';
    case SCHEDULE_INTERVIEW = 'SCHEDULE_INTERVIEW';
    case CHANGE_SCORE = 'CHANGE_SCORE';
    case APPROVE_PLENARY = 'APPROVE_PLENARY';
    case GENERATE_SK = 'GENERATE_SK';
    case SYNC_SIAKAD = 'SYNC_SIAKAD';
    case SYNC_PDDIKTI = 'SYNC_PDDIKTI';
}
